# Generated by Django 4.0.6 on 2022-08-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkorder',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='largefile/'),
        ),
        migrations.AlterField(
            model_name='chunkorder',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='zips/'),
        ),
    ]
