# Generated by Django 4.0.6 on 2022-08-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkapp', '0002_chunkorder_file_alter_chunkorder_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkorder',
            name='chunk_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
