# Generated by Django 4.0.6 on 2022-08-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunkapp', '0003_alter_chunkorder_chunk_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunkorder',
            name='zip_file',
        ),
    ]
