# Generated by Django 4.0.6 on 2022-08-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunkapp', '0004_remove_chunkorder_zip_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunkorder',
            options={'ordering': ['created']},
        ),
    ]
