# Generated by Django 4.0.6 on 2022-08-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunkapp', '0005_alter_chunkorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunkorder',
            options={'ordering': ['-created']},
        ),
    ]
