# Generated by Django 4.0.6 on 2022-08-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkapp', '0006_alter_chunkorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkorder',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
